FROM quay.io/aptible/ubuntu:<%= ENV.fetch 'OS_VERSION' %>

RUN apt-get update && apt-get -y install curl ruby

ENV TAG <%= ENV.fetch 'TAG' %>
ENV KIBANA_VERSION <%= ENV.fetch 'KIBANA_VERSION' %>
ENV KIBANA_DOWNLOAD <%= ENV.fetch 'KIBANA_DOWNLOAD' %>
ENV KIBANA_SHA1SUM <%= ENV.fetch 'KIBANA_SHA1SUM' %>

RUN curl -fsSL "${KIBANA_DOWNLOAD}" -o ./installer.tar.gz && \
    echo "${KIBANA_SHA1SUM}  installer.tar.gz" | sha1sum -c - && \
    mkdir /opt/kibana && \
    tar xzf "installer.tar.gz" -C /opt/kibana --strip-components 1 && \
    rm "installer.tar.gz"

RUN rm "/opt/kibana/config/kibana.yml" 
ADD templates/kibana.yml.erb /opt/kibana/config/


ADD bin /usr/bin/
RUN chmod 700 /usr/bin/run-kibana.sh
RUN chmod 700 /usr/bin/check-es-version.sh
ADD files/.aptible.yml /.aptible/

# Add tests. Those won't run as part of the build because customers don't need to run
# them when deploying, but they'll be run in test.sh
ADD test /tmp/test

EXPOSE 80

CMD ["/usr/bin/run-kibana.sh"]
